<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\AgenceImmobiliereController::index'], [], [['text', '/']], [], []],
    'biens_immobiliers' => [[], ['_controller' => 'App\\Controller\\AgenceImmobiliereController::biens_immobiliers'], [], [['text', '/biens_immobiliers']], [], []],
    'biens_immobiliers_suppression' => [['id'], ['_controller' => 'App\\Controller\\AgenceImmobiliereController::suppression'], ['id' => '[0-9]+'], [['variable', '/', '[0-9]+', 'id', true], ['text', '/biens_immobiliers']], [], []],
    'biens_immobiliers_modification' => [['id'], ['_controller' => 'App\\Controller\\AgenceImmobiliereController::modification'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/biens_immobiliers/edit']], [], []],
    'biens_immobiliers_lire' => [['id'], ['_controller' => 'App\\Controller\\AgenceImmobiliereController::bien'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/biens_immobiliers']], [], []],
    'app_reservation' => [['id'], ['_controller' => 'App\\Controller\\AgenceImmobiliereController::reservation'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/biens_immobiliers/reservation']], [], []],
    'filtreImmoByMax' => [[], ['_controller' => 'App\\Controller\\AgenceImmobiliereController::filtreImmoByMax'], [], [['text', '/immo']], [], []],
    'authentification' => [[], ['_controller' => 'App\\Controller\\AuthentificationController::authentification'], [], [['text', '/authentification']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\AuthentificationController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\AuthentificationController::logout'], [], [['text', '/logout']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
];
